baseurl = "https://pruebaela1.netlify.com/"
title = "Tenemos ELA"
theme = "hugo-universal-theme"
themesDir = "themes"
languageCode = "es-UY"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "es"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "En construcción"
    url  = "/"
    weight = 1
